### PR TITLE
Rename __main__ to __main__.py #420

### PR DESCRIPTION
**Pull request by AnkurDedania**
Rename **main** to **main**.py #420

### CODE REVIEW

**Comment by sebix** [comment]
Why does this exists?

**Comment by AbsoluteMSTR** [comment]
allows you to call isort from python. Example, `python3 -m isort` instead of just calling `isort` useful if you want to explicitly make python use python3 instead of 2.x. Since `pip install -U isort` and `pip3 install -U isort` overwrite each other.

**Comment by MinchinWeb** [comment]
Turns out this already exists, so I'll add my :+1: rather than opening another pull request!

**Comment by timothycrosley** [comment]
Looks good, thanks!

**Pull request merged**
