### PR TITLE
Read configuration from XDG_CONFIG_HOME

### PR DESCRIPTION
**Pull request by r-darwish**
In addition to `~/.isort.cfg`, isort will try to read a configuration file from
`$XDG_CONFIG_HOME/isort.cfg`

### CODE REVIEW

**Comment by r-darwish** [comment]
Waiting for #782 in order to use the xdg package.

**Comment by jdufresne** [comment]
appdirs may be a suitable alternative to consider. https://github.com/ActiveState/appdirs

It is well established, cross platform (Windows), and supports all current Pythons.

**Comment by r-darwish** [comment]
appdirs returns `~/Library/Application Support` in macOS instead of
`$XDG_CONFIG_HOME/isort.cfg`. Is that acceptable?

**Comment by jdufresne** [comment]
I don't use macOS, but I gather that is the typical spot for configuration files. If so, then yeah, that makes sense to me.

**Comment by r-darwish** [comment]
It's the typical spot for GUI applications. Command line applications such as fish or git still look
for their configuration file in `~/.config` in macOS. I'll do [this](https://github.com/ActiveState/appdirs/issues/78#issuecomment-366947045)

**Comment by timothycrosley** [comment]
Looks good! Thank you!

**Pull request merged**
