### PR TITLE
Add configuration to ensure a newline before each comment

### PR DESCRIPTION
**Pull request by FuegoFro**
This adds a `ensure_newline_before_comments` configuration that matches the format that `black` imposes (for better or worse) and allows `isort` to be used with `black` without any thrashing/conflicts with regards to blank lines before comments.

Should help address https://github.com/psf/black/issues/251

### CODE REVIEW

**Comment by xmnlab** [comment]
this implementation would be very helpful.
is there any any estimate to move that forward?

**Comment by timothycrosley** [comment]
@FuegoFro This is great! Thanks for working on this!

**Comment by hugovk** [comment]
Confirmed current master fixes the problem. 

Is there a schedule for the next release? It would help unblock formatting pip with Black+isort.

Thanks!

**Comment by timothycrosley** [comment]
@hugovk I can get it scheduled comfortably for 2 weeks for now. if it is really urgent I can try to get it the release in good shape within a week. I hate to block the work on pip!

Let me know,

Thanks!

~Timothy

**Comment by hugovk** [comment]
Thanks! I don't know how long it'll take for the PR to be reviewed (it's big!) so let's ask over there: https://github.com/pypa/pip/pull/7084.

**Comment by pradyunsg** [comment]
> I hate to block the work on pip!

Hi hi.

Don't worry about that -- We can easily wait for the next release of isort for doing this, so please feel free to make the release at a time that's comfortable for you. No pressure from our end. :)

AFAIK, we're in no hurry to adopt black (we already use isort!) even though I don't think anyone is opposed to it at this point. 🙃

Thanks for all of your (and other contributors') work on isort!

**Comment by FuegoFro** [comment]
Hey! Just wondering if there was any news on a release that has this change in it. No rush! Just curious 🙂

**Comment by timothycrosley** [comment]
Hi @FuegoFro,

I've finished the other project that I wanted to finish up before the release: https://timothycrosley.com/project-7-streamdeck_ui and switched to spending all my OpenSource time working on preparing the isort 5.0.0 release. I hope to have it wrapped up soon.

Thanks!

~Timothy

**Comment by FuegoFro** [comment]
Hey there! Just checking in again to see if any progress has been made on a new release 🙂

**Comment by pradyunsg** [comment]
@timothycrosley Gentle nudge on 5.0.0. :)

Are there any release blocker issues that we could help you with?

**Comment by ssbarnea** [comment]
Yes, please make a new release as we cannot use unreleased code in production.

**Comment by julien-c** [comment]
Any news on this? Thanks!

**Comment by thomwolf** [comment]
Can we help with the release somehow?

**Comment by jaklan** [comment]
@timothycrosley ANY answer would be really appreciated and much better than just ignoring people 🙄

**Comment by jonathanunderwood** [comment]
@timothycrosley would it be possible to push a 4.3.x release with this feature added ahead of the move to 5.0.0? This is currently blocking projects from using isort where we would love to be able to make use of isort and black together.

**Comment by johnthagen** [comment]
Looks like 5.0.0 is releasing tomorrow: https://github.com/timothycrosley/isort/commit/2ea917e8dad7116584c0c5927b43f25ca300f819

**Pull request merged**
