### PR TITLE
Issue 1160: remove redundant as imports

### PR DESCRIPTION
**Pull request by ucodery**

### CODE REVIEW

**Comment by ucodery** [comment]
I still have an open question as to how this logic would be expected to interact with "keep_direct_and_as_imports", specifically when it is False.
This behavior is changed, but to me the result is pretty obvious
```python
import isort
import isort as isort
# now produces -->
import isort
```
This behavior is also changed, and IMO makes for cleaner code, but would probably surprise me if I had used the keep_direct_and_as_imports=False option.
```python
import isort as isort
# now produces -->
import isort
```

Given that the above, simpler code, was achieved without additional special cases in output.py, and that I opened #1192, I have submitted with this new behavior.

**Comment by graingert** [comment]
@ucodery this `import x as x` syntax is used in mypy with https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport

**Comment by ucodery** [comment]
@graingert interesting, it is good to see some documentation why this shadowing is used in some places. Given the MyPy convention, would you still agree that the first example is correct? I still see two import lines importing the same thing, and not changing the namespace, as a lint error, and I still see defaulting to the shorter as more straightforward.

**Comment by timothycrosley** [comment]
Thanks for all the input and work here! Took the ideas, and additional feedback, and this is now incorporated under this flag: https://timothycrosley.github.io/isort/docs/configuration/options/#remove-redundant-aliases

**Pull request closed without merging**
