### PR TITLE
Too many newlines

### PR DESCRIPTION
**Pull request by do3cc**
This is not meant as a PR, but a bug report.

### CODE REVIEW

**Comment by saily** [comment]
Thanks for writing these testcases to identify the problem. i ran into this while working on `plone.recipe.codeanalysis`. we get a lot of extra lines reported there. Issue:

- https://travis-ci.org/timothycrosley/isort/jobs/78731166#L155
- https://travis-ci.org/plone/plone.recipe.codeanalysis/jobs/78652480#L376

@timothycrosley do you have an idea about this?

**Comment by timothycrosley** [comment]
@do3cc Thanks for reporting this issue and providing test cases! @saily thanks for the additional data point, I'm sorry to hear you are also running into this issue, ill add these test cases and fix before the next release Thanks!

**Comment by gforcada** [comment]
This is already fixed (thanks @timothycrosley !) would it be possible to get a release? :smile:

**Comment by timothycrosley** [comment]
@gforcada Welcome! Just released 4.2.0, which should fix this issue

Thanks!

~Timothy

**Comment by gforcada** [comment]
Thanks!

**Comment by do3cc** [comment]
Thanks!

**Pull request closed without merging**
