### PR TITLE
Add linting with flake8 in Travis

### LINKED ISSUE #551: Add flake8 to the Travis run
I think it would be useful to add flake8 to the Travis run, since it would have caught some of the syntax errors that resulted in the hotfix releases today.

Whilst in an ideal world there would be 100% test coverage, linters help fill in the gaps, plus spot potential unused variable/imports cleanup.

### PR DESCRIPTION
**Pull request by alexwlchan**
My requires.io has been nagging about all the extra releases today. If it really was just issues that would be caught by linting, let me help you out with that so it doesn't happen again. :-)

Resolves #551.

### CODE REVIEW

**Comment by timothycrosley** [comment]
Linting will def help! The biggest issue was really that isort hasn't had a major release in over a year(!), assuming a more consistent release schedule + linting, and things should be much smoother going forward.

**Comment by alexwlchan** [comment]
Travis fails, which proves the test works! Commits just pushed should resolve the lint errors it spotted.

**Comment by alexwlchan** [comment]
(oops)

**Comment by timothycrosley** [comment]
Looks great, thanks!

**Comment by edmorley** [comment]
Many thanks!

> My requires.io has been nagging about all the extra releases today

Yeah pyup bot has been having fun today too in our repo (and [some others](https://github.com/pulls?utf8=%E2%9C%93&q=isort+author%3Apyup-bot+created%3A2017-06-01)) :-)

**Pull request merged**
