### PR TITLE
Add new Python 3.7 modules to known standard library modules

### PR DESCRIPTION
**Pull request by brycepg**
https://docs.python.org/3/whatsnew/3.7.html

### CODE REVIEW

**Comment by jbaiter** [comment]
Any chance for this to get merged?

**Comment by timothycrosley** [comment]
Sorry for the long delay, this looks great! Merged

**Comment by lukaselmer** [comment]
Thank you @timothycrosley 👍

**Comment by richin13** [comment]
Hey @timothycrosley, which release of `isort` includes this fix? I'm running `4.3.4` but I'm still experiencing the issue of `dataclasses` not being recognize as part of the standard lib

FYI, I installed this using poetry

**Comment by webknjaz** [comment]
`pylint` fails to identify `contextvars` as stdlib module as well. Any plans to release a new version? @timothycrosley? @jdufresne?

**Comment by jdufresne** [comment]
Sorry. I'd like to but I don't have the PyPI permissions necessary to spin a release.

**Comment by webknjaz** [comment]
But who does then? Would you be interested in a contribution setting up publishing flow in Travis so any of the maintainers could publish by pushing a new tag?

**Comment by jdufresne** [comment]
> But who does then?

I believe only @timothycrosley has permission to upload to PyPI.

> Would you be interested in a contribution setting up publishing flow in Travis so any of the maintainers could publish by pushing a new tag?

That would be great!

**Pull request merged**
