### PR TITLE
force grid wrapping regardles of line length

### LINKED ISSUE #249: pull request was reverted in bad release merge
#222 (003a978) was deleted in ~~the merge at 7b1bb99 (for release/3.9.4)~~ somewhere, i'm still looking for it.

### PR DESCRIPTION
**Pull request by NorthIsUp**
fixes #249

### CODE REVIEW

**Comment by NorthIsUp** [comment]
any thoughts on this?

**Comment by NorthIsUp** [comment]
rebased onto develop

**Comment by timothycrosley** [comment]
Hi @NorthIsUp, so sorry I have gotten to this earlier! If all tests pass will merge - thanks again for working on this improvement

~Tim

**Comment by timothycrosley** [comment]
Tests passed - change merged - thanks again!

**Pull request merged**
