### PR TITLE
Fix order of sections when loading them from config file

### PR DESCRIPTION
**Pull request by danbaragan**

### CODE REVIEW

**Comment by mjtamlyn** [comment]
This resolves the issue for me.

**Comment by w0rp** [comment]
:+1: 

Unless it breaks something I don't know about, merge it.

**Comment by timothycrosley** [comment]
Looks perfect, thanks so much for implementing a solution - I know a lot of users will apreciate this! +1

~Timothy

**Comment by ychab** [comment]
Works like a charm, thks !

**Comment by danbaragan** [comment]
You're welcome. Thank you for the isort all together :)

**Pull request merged**
